BXMSPROD-753: last changes in mailer.groovy
Ginxo/jenkins-pipeline-shared-libraries pull request #3
Opened 2020-05-25 13:45 UTC by mbiarnes

2020-05-25 14:03 UTC, Ginxo requested changes
please review

2020-05-25 14:03 UTC, Ginxo commented on vars/mailer.groovy
> +def sendEmail_failedPR(pr_type) {
The problem here is other projects are using the method already
https://github.com/kiegroup/kogito-runtimes/blob/f4c84914b945e56c34d20f3ea88c725d7bfab968/Jenkinsfile#L75
So I would add pr_type as an optional argument plus the null check `${pr_type ?: ''}`

2020-05-25 14:03 UTC, Ginxo commented on vars/mailer.groovy
> +def sendEmail_fixedPR(pr_type) {
the same here https://github.com/kiegroup/kogito-runtimes/blob/f4c84914b945e56c34d20f3ea88c725d7bfab968/Jenkinsfile#L87

2020-05-26 08:02 UTC, mbiarnes reviewed
in my understanding (and this of course can be completele wrong) if I put in a method 
def method (parameter = value) { - this means if the parameter is not passed the parameter gets automatically the value - this is what I want 
If i is wrong please help me how to d it right

2020-05-26 08:02 UTC, mbiarnes commented on vars/mailer.groovy
> +def sendEmail_failedPR(pr_type) {
@ginxo sorry - no idea how to do this

2020-06-02 12:36 UTC, Ginxo approved these changes

2020-06-02 12:36 UTC, Ginxo commented on vars/mailer.groovy
> +def sendEmail_failedPR(String additionalSubject = "PR") {
this is like so, exactly, but I would do `String additionalSubject = null` instead.
And would replace `subject: "${additionalSubject} #$ghprbPullId of $ghprbGhRepository: $ghprbPullTitle failed"` by `subject: "${additionalSubject ? additionalSubject + ' '  : ''}#$ghprbPullId of $ghprbGhRepository: $ghprbPullTitle failed"`
wdyt?

2020-06-02 12:36 UTC, Ginxo commented on vars/mailer.groovy
> +            subject: "${additionalSubject.trim() ?: 'PR'} #$ghprbPullId of $ghprbGhRepository: $ghprbPullTitle failed",
`${additionalSubject.trim() ?: 'PR'}` will produce a NullPointerException in case you send a null to the method.
You can try it here https://www.tutorialspoint.com/execute_groovy_online.php to paste this
```
def sendEmail_failedPR(String additionalSubject = '' )
{
    return "${additionalSubject.trim() ?: 'PR'} whatever"
}
println("sendEmail_failedPR() " +sendEmail_failedPR())
println("sendEmail_failedPR('PEPE') " +sendEmail_failedPR('PEPE'))
println("sendEmail_failedPR(null) " +sendEmail_failedPR(null))
```
So I would say
```
def sendEmail_failedPR(String additionalSubject = null ) {
    emailext(	    
        subject: "${additionalSubject?.trim() ?: ''} #$ghprbPullId of $ghprbGhRepository: $ghprbPullTitle failed"
```
it's a much better approach and send 'PR' in the PR_TYPE parameter whenever you require it

The same for the rest of methods

2020-06-02 12:39 UTC, merged